### ISSUE TITLE
StepException after valid sheet skip operation

### ISSUE THREAD

**Issue by JalonSolov** [Audiveris/audiveris#132]
Preface:  New to Audiveris, looks very promising!  However...

Load a PDF of sheet music with a cover sheet (no music, just a description - any non-music sheet should do).  Tell Audiveris to translate the book.

It asks if you want to skip the first page (the cover).

Click 'Yes'.

Instead of simply proceeding to the next page, it first throws an exception, then proceeds.  Does the same thing with code from 'master' and 'development' branches.

INFO  [Blue Skies]                 BasicBook 270  | 8 sheets in D:\PDFs\Blue Skies.pdf
INFO  [Blue Skies#1]                 BasicBook 993  | Loaded image 1 2472x3224 from D:\PDFs\Blue Skies.pdf
INFO  [Blue Skies]                 BasicBook 1078 | Book reaching PAGE on sheets:[#1#2#3#4#5#6#7#8]
WARN  [Blue Skies#1]                 BasicStub 222  | Blue Skies#1 With an interline value of 7 pixels, either this sheet contains no staves, or the picture resolution is too low (try 300 DPI).
INFO  [Blue Skies#1]                 BasicStub 493  | Sheet Blue Skies#1 flagged as invalid.
INFO  [Blue Skies#1]                 BasicStub 202  | Sheet closed
WARN  [Blue Skies#1]                 BasicStub 841  | Error in SCALE java.util.concurrent.ExecutionException: org.audiveris.omr.step.StepException: Sheet removed
java.util.concurrent.ExecutionException: org.audiveris.omr.step.StepException: Sheet removed
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at org.audiveris.omr.sheet.BasicStub.doOneStep(BasicStub.java:824)
	at org.audiveris.omr.sheet.BasicStub.reachStep(BasicStub.java:564)
	at org.audiveris.omr.sheet.BasicBook.reachBookStep(BasicBook.java:1145)
	at org.audiveris.omr.sheet.BasicBook.transcribe(BasicBook.java:1518)
	at org.audiveris.omr.sheet.ui.BookActions$TranscribeBookTask.doInBackground(BookActions.java:2056)
	at org.audiveris.omr.sheet.ui.BookActions$TranscribeBookTask.doInBackground(BookActions.java:2033)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.audiveris.omr.step.StepException: Sheet removed
	at org.audiveris.omr.sheet.BasicStub.decideOnRemoval(BasicStub.java:234)
	at org.audiveris.omr.sheet.ScaleBuilder.checkResolution(ScaleBuilder.java:197)
	at org.audiveris.omr.sheet.ScaleBuilder.retrieveScale(ScaleBuilder.java:167)
	at org.audiveris.omr.step.ScaleStep.doit(ScaleStep.java:85)
	at org.audiveris.omr.step.Step.doit(Step.java:184)
	at org.audiveris.omr.sheet.BasicStub$3.call(BasicStub.java:814)
	at org.audiveris.omr.sheet.BasicStub$3.call(BasicStub.java:802)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 common frames omitted
INFO  [Blue Skies#1]                 BasicStub 846  | Cause org.audiveris.omr.step.StepException: Sheet removed
INFO  [Blue Skies#1]                 BasicStub 571  | StepException detected in [SCALE, GRID, HEADERS, STEM_SEEDS, BEAMS, LEDGERS, HEADS, STEMS, REDUCTION, CUE_BEAMS, TEXTS, MEASURES, CHORDS, CURVES, SYMBOLS, LINKS, RHYTHMS, PAGE]
INFO  [Blue Skies#2]                 BasicBook 993  | Loaded image 2 2472x3224 from D:\PDFs\Blue Skies.pdf
...

**Comment by maximumspatium** [comment]
Did you try to select the non-music sheet and invalidate it by selecting _**Invalidate sheet**_ command from Sheet menu?

**Comment by hbitteur** [comment]
@JalonSolov This StepException being raised is the standard way to stop the processing pipeline of a sheet when some exceptional condition (musicwise) is encountered deep in sheet processing. Here the sheet, during the SCALE step, is discovered as containing no music.

So don't be afraid, this step-halting behavior was chosen by design. See https://github.com/Audiveris/audiveris/blob/master/src/main/org/audiveris/omr/step/StepException.java

Now, this is old code. I understand that you would feel more comfortable if no StepException stack dump was shown in Audiveris output. I'm putting this modification on the todo list.

**Comment by JalonSolov** [comment]
As I said, I'm new to Audiveris, but not to code... I've been programming for 40+ years.  :-)

I had no idea the Invalidate Sheet command existed until the first reply, so I tried that.  After I did, I told Audiveris to translate the book... and got exactly the same results as above.

My purpose for reporting this, yes, was to avoid seeing an Exception for a valid, user-confirmed action.  Something that should be caught and handled by the code before dumping a traceback to the output.

I understand things take time when working with old code.  I just tend to report problems as I find them.  Thanks for putting it on the list.

**Comment by hbitteur** [comment]
Fixed in development commit 13b8d23dd4a5f749c48acb171234e048d7821c87
Just to make sure, would you be kind enough to retry your precise example and confirm the result?

FYI, Audiveris development started very unformally in 1998 because my kids started to play music They were able to read standard scores, something I could not  (I could read tablatures only). So I started to develop what I thought would be a tiny program just to allow me to play music with them...

**Comment by JalonSolov** [comment]
Some of the best programs start that way.  :-)  Just something small for the kids, then it takes on a life of it's own.

I wish to commend you on this.  I paid for "SharpEye OCR" many years ago, and Audiveris does a comparable job in it's latest version.  Still not perfect, but getting closer.

Ok, did a git pull to get your changes (2 files - BasicStub.java and Staff.java) since my last pull.

Sorry... nearly identical exception:

java.util.concurrent.ExecutionException: org.audiveris.omr.step.StepException: Sheet removed
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at org.audiveris.omr.sheet.BasicStub.doOneStep(BasicStub.java:824)
	at org.audiveris.omr.sheet.BasicStub.reachStep(BasicStub.java:564)
	at org.audiveris.omr.sheet.BasicBook.reachBookStep(BasicBook.java:1145)
	at org.audiveris.omr.sheet.BasicBook.transcribe(BasicBook.java:1518)
	at org.audiveris.omr.sheet.ui.BookActions$TranscribeBookTask.doInBackground(BookActions.java:2051)
	at org.audiveris.omr.sheet.ui.BookActions$TranscribeBookTask.doInBackground(BookActions.java:2028)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.audiveris.omr.step.StepException: Sheet removed
	at org.audiveris.omr.sheet.BasicStub.decideOnRemoval(BasicStub.java:234)
	at org.audiveris.omr.sheet.ScaleBuilder.checkResolution(ScaleBuilder.java:197)
	at org.audiveris.omr.sheet.ScaleBuilder.retrieveScale(ScaleBuilder.java:167)
	at org.audiveris.omr.step.ScaleStep.doit(ScaleStep.java:85)
	at org.audiveris.omr.step.Step.doit(Step.java:184)
	at org.audiveris.omr.sheet.BasicStub$3.call(BasicStub.java:814)
	at org.audiveris.omr.sheet.BasicStub$3.call(BasicStub.java:802)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 common frames omitted

I would be willing to send you this PDF if you want to use it to debug (this file causes a few other exceptions I haven't reported, yet).  However, it would need to be private, to avoid copyright issues.

**Comment by hbitteur** [comment]
Yes please send me your example, so that we can sort this out.
My private email is herve dot bitteur at audiveris dot org

**Comment by hbitteur** [comment]
Thanks for your concrete Blue Skies example.
What happened is that `StepException` got wrapped into an `ExecutionException` (thrown when attempting to retrieve the result of a task that aborted by throwing an exception).

This is now correctly handled in commit 755d1a403364da07651aa0b5235356c10764144b

**Comment by JalonSolov** [comment]
Thanks!  I pulled the code and it now acts as I expected.  Other changes took care of most of the other exceptions I've been seeing with that file - I entered issue for the remaining 3.
