### ISSUE TITLE
Invalidate sheet does not suppress sheet when exporting score

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#284]
[Bei mir bist Du schön.zip](https://github.com/Audiveris/audiveris/files/3171445/Bei.mir.bist.Du.schon.zip)

This score has a problem with proper detection of the system in the 5th page. Therefore I tried to invalidate this page, because this causes a complete wrong system structure (MuseScore creates systems with 15 lines of it). But invalidate seems not to suppress this page.

**Comment by hbitteur** [comment]
Gasp! The actual call to this feature had disappeared. Don't ask me why.
Situation is now back to normal in commit c4f43442467b227507ae2c40ab8c5c89f27e25fd on "development" branch.

Side note: Perhaps an update to 5.1 should be done shortly (September?) to publish all these small hotfixes in the official "master" branch and in the Windows 5.1 installers as well.

**Comment by Bacchushlg** [comment]
V5.1: Yes, very good idea.
I don't see the commit. Did you push it?

**Comment by Bacchushlg** [comment]
Yes, feature works again as expected

**Comment by hbitteur** [comment]
The original problem was a mis-recognition of the first system of sheet 5, due to a poor vertical barline connection between first and second staff. The 3-staff system was not recognized as a single system but led to a 1-staff system followed by a 2-staff system.

I worked on this example and implemented a "system merge" feature that the user can perform manually. By pointing on the upper system "chunk", the right-click context menu now includes a new "system sub-menu" which allows to merge the selected system with the one located immediately below.
A few checks are made to ensure compatibility between the two "system chunks" (existence of a system below, same number of measures, vertical alignment of measures ends).

The operation can be undone / redone at will.

I pushed this feature into the "development" branch, via the d171c196aec12d2a68e0a34a9ef8add0a1fc78ce commit.

**Comment by Bacchushlg** [comment]
I just tried this feature. Works perfect!
But... when I export the example file, I still get a messy xml output file. 
When I then invalidate sheet 5 and export again, the export is fine.

It seems that something stays messy inside, even after correction of the systems.

**Comment by hbitteur** [comment]
Sorry Baruch. During the system merge, I had left wrong part information behind, resulting in 10 different logical parts in sheet 5, instead of 2.

This is now fixed, export to MuseScore seems to work fine, but please double-check on your side.
Bug fix is in commit b8b84dd58ec59600cc7507b448cca76b41f52b74 on development branch.

**Comment by Bacchushlg** [comment]
works fine now!
