### ISSUE TITLE
Cannot recognize CJK files name

### ISSUE THREAD

**Issue by qnach** [Audiveris/audiveris#825]
Need to upgrade to UTF-8 fonts

**Comment by hbitteur** [comment]
@qnach 

I have just published a 5.6.3 pre-release. Here is a [direct link](https://github.com/Audiveris/audiveris/releases/tag/5.6.3) in the releases page.
Please download and install (after having uninstalled the previous version).

It should now correctly handle the history of file names, even if these file names contain chinese characters. 
Please check this and post your results.

Beware: this will only work for the NEW file names put in your history, for example by loading an input file.
The old file names are still there and corrupted.
But this is just a cache for the most recent files. The cache is limited to 10 file names, so the old corrupted names should quickly disappear.

Or, you can immediately purge the cache, by manually editing the `run.properties` file (see it's precise location in my previous message). Just remove or comment out  the line that starts with `org.audiveris.omr.sheet.BookManager.imageHistory`

**Comment by hbitteur** [comment]
Hmm, I suspect you did not really understand my last message. I said:
>Beware: this will only work for the NEW file names put in your history, for example by loading an input file.
The old file names are still there and corrupted.
But this is just a cache for the most recent files. The cache is limited to 10 file names, so the old corrupted names should quickly disappear. 

Comparing your initial image and your recent image of the menu `File | Recent inputs`, the list of file names is **_identical_** in these images!
In other words, you have not modified the file history, which is still corrupted! So, you are reading corrupted items.

Please  load files, the same files or new files, but NOT VIA HISTORY.
More precisely **use the menu item `File | Input` and not the menu item `File | Recent inputs`**:
- `File | Input` adds a new item at the beginning of history (and discards the oldest one at the end). Gradually, your history will get clean.
- `File | Recent inputs` reuses (perhaps corrupted) items from history and does not modify/clean it.

**Comment by qnach** [comment]
o.k. I tried to open a new file

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/52c72ded-96a3-4949-ae21-c6053d09c2ea" />

The file name at the bottom screen displayed correctly. But the opening window is still incorrect.

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/50f38b5a-a42d-44a6-ad84-2bc3d8ae834e" />

**Comment by hbitteur** [comment]
@qnach 
Remember that, on my side, I cannot test these file names with special characters.
So we have to work in parallel, and the good news is that we are making progress.
Let's address the problems one by one.

First, the easy ones:
1. The file you have loaded contains an image of size 8775 x 12750 = 111,881,250 pixels. This is way above the upper limit of 20,000,000 pixels accepted by Audiveris. Consequently, the program refuses to process this huge file.
2. The image represents a score of very poor quality, there is no chance that an OMR program could process such a bad input.

So, for the next tests, please select much smaller files with much better quality.

Second, the handling of chinese characters:
1. A good point is the fact that the log window lists the (huge) file with what seems a correct name with chinese characters.    
    Could you confirm this?
3. What about the input history? Even though you have not been able to process this huge file, its name should now be in the input history.   
   Could you check this, by trying the menu `File | Recent inputs` and posting the image.
5. Could you have a look in the `run.properties` file with a text editor?   
   Please post the image.
7. What puzzles me is your initial Open dialog (your first image). The content it displays for the selected `Youtube` folder, has some (chinese?)  characters replaced with blank rectangles.  The code for this dialog is not mine, it's a standard Java swing dialog. I will need to investigate how to customize it to make it display chinese characters.
 
That's all for now.

**Comment by qnach** [comment]
Reply to your questions:
1. Yes, the Chinese characters on the log file and the left top Window screen heading are all correct.

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/002c37a9-75a6-4bf7-9ca5-dba828dd0aa8" />

2. Input history, as said, is incorrect.

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/df04c5c9-b063-444f-9094-ac857131f57b" />

3. Cannot find  run.properties

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/994d4f2f-a031-4e8f-ab67-684ebdb84825" />

4. Unrecognized Chinese characters are replaced by squares. It might because you did not use the correct font. 
The font you used is not Chinese font.  We have nowhere to change the font used by the program. 
Most modern software have a choice to change the language at the option manual, which can even change the heading language.
Over there we can change the font too.

**Comment by hbitteur** [comment]
Yes, the content of `run.properties` file is correct.

The problem is that some parts of Audiveris graphic interface (like the list of recent input files) don't display the chinese characters correctly, while some other parts are OK (like the frame title or the log window).

I'm still investigating.

**Comment by qnach** [comment]
it is the font, as i said

**Comment by hbitteur** [comment]
@qnach 

We can change the default Locale in Audiveris, via the `Tools | Preferences` menu.
Today, the choice is between "en" (the default), and "fr".

But this is different from the question of _font_.
It allows to customize the _language_ in which Audiveris messages are shown.

This is done via a set of `.properties` files located in the `resources` folders.
There are today 33 such files per language in Audiveris application.

For instance, the Java class `AboutAction`, which displays the "About" information provides, in the sibling `resources `folder:
- `AboutAction.properties` for the default (Englich) language,
- `AboutAction_fr.properties` for the fr (French) language.

If someone volunteers to support the Chinese language, all this person has to do is to provide a proper:
- `AboutAction_zh.properties` file.

And do the same thing for the other 32 files...

FYI, here is the content of `AboutAction.properties`:
```
# ---------------------------------------------------------------------------- #
#                                                                              #
#                  A b o u t A c t i o n . p r o p e r t i e s                 #
#                                                                              #
# ---------------------------------------------------------------------------- #

# This file gathers resources to be injected in the AboutAction class
#
# This is the generic version

# Resources for AboutBox
# ----------------------

AboutDialog.title = About ${Application.name}
AboutDialog.copied = Content copied to clipboard!

aboutTitleLabel.text = ${Application.name}

descriptionLabel.text = Role:
descriptionTextField.text = ${Application.description}

versionLabel.text = Version:

classesLabel.text = Container:

homeLabel.text = Home page:

projectLabel.text = Dev. project:

licenseLabel.text = Software license:

ocrLabel.text = OCR engine:
ocrFolderLabel.text = OCR folder:

javaVendorLabel.text = Java vendor:
javaVersionLabel.text = Java version:
javaRuntimeLabel.text = Java runtime:
javaVmLabel.text = Java VM:

osLabel.text = Operating System:
osArchLabel.text = Architecture:
```

And the content of `AboutAction_fr.properties`:

```
# ---------------------------------------------------------------------------- #
#                                                                              #
#              A b o u t A c t i o n _ f r . p r o p e r t i e s               #
#                                                                              #
# ---------------------------------------------------------------------------- #

# This file gathers resources to be injected in the AboutAction class
#
# This is the "fr" version

# Resources for AboutBox
# ----------------------

AboutDialog.title = A propos d'${Application.name}
AboutDialog.copied = Contenu copi\u00e9 dans le presse-papiers !

descriptionLabel.text = R\u00f4le :

versionLabel.text = Version :

classesLabel.text = Conteneur:

homeLabel.text = Site Web :

projectLabel.text = Projet :

licenseLabel.text = Licence du logiciel :

ocrLabel.text = Moteur OCR :
ocrFolderLabel.text = Donn\u00e9es OCR :

javaVendorLabel.text = Fournisseur Java :
javaVersionLabel.text = Version Java :
javaRuntimeLabel.text = Runtime java :
javaVmLabel.text = Machine virtuelle Java :

osLabel.text = Syst\u00e8me d'exploitation :
osArchLabel.text = Architecture :
```
